### ISSUE TITLE
数据库建表语句

### ISSUE THREAD

**Issue by xiaohui2856** [hemin1003/aylson-parent#1]
请问，可以提供数据库建表语句吗

**Comment by hemin1003** [comment]
可以啊。留一个邮箱地址，我发给你

**Comment by actionchen** [comment]
您好，是否也可以提供数据库建表语句給我，感謝。。。
我的email：
chen.action@gmail.com

**Comment by hemin1003** [comment]
请下载：https://github.com/hemin1003/aylson-parent/blob/master/cfdb_2018-01-08.sql.gz
